apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../nodeport

patchesJson6902:
  - path: remove-ldap.json
    target:
      kind: Service
      name: ds389-nodeport
      version: v1
