apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sa.yaml
  - service.yaml
  - statefulset.yaml

commonLabels:
  app.kubernetes.io/name: 389ds
  app.kubernetes.io/version: 'fedora33'

images:
  - name: 389ds:latest
    newName: ghcr.io/gabibbo97/389ds
    newTag: fedora33

secretGenerator:
  - name: ds389
    env: 389ds.env
