apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sa.yaml
  - service.yaml
  - statefulset.yaml

commonLabels:
  app.kubernetes.io/name: 389ds
  app.kubernetes.io/version: '1.4'

images:
  - name: 389ds:latest
    newName: 389ds/dirsrv
    newTag: '1.4'

secretGenerator:
  - name: ds389
    env: 389ds.env
