apiVersion: v1
kind: Service
metadata:
  name: ds389
spec:
  clusterIP: None
  ports:
    - appProtocol: ldap
      name: ldap
      port: 389
      targetPort: 3389
    - appProtocol: ldaps
      name: ldaps
      port: 636
      targetPort: 3636
